spring.application.name=backend
spring.config.import=classpath:env.properties

# database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

#jpa
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

#Dev tools
spring.devtools.restart.enabled=false

app.secret.key=${SECRET_KEY}

#github
github.client.id=${CLIENT_ID}
github.client.secret=${CLIENT_SECRET}
github.redirect.uri=http://localhost:8080/github/callback

